# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('troll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('USER_ID', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('USER_PW', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.EmailField(max_length=30)),
                ('FRIEND_ID', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.EmailField(max_length=30)),
                ('DATE', models.DateTimeField(default=django.utils.timezone.now)),
                ('YTB_LINK', models.TextField()),
            ],
        ),
    ]
