# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troll', '0002_user_userfriend_usermusic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfriend',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usermusic',
            name='USER_ID',
        ),
        migrations.AddField(
            model_name='userfriend',
            name='USER_FRIEND',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='USER_ID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfriend',
            name='FRIEND_ID',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userfriend',
            name='USER_ID',
            field=models.CharField(max_length=30),
        ),
    ]
